### ISSUE TITLE
User Story 6: Design

### ISSUE THREAD

**Issue by e-rmkt** [e-rmkt/capstone-project-travel-app#14]
## Value proposition

`As a` travel enthusiast
`I want to` have a well structured and appealing app
`so that`  I can find my way around and enjoy using it

## Description

- final design will be end product of this US

## Acceptance criteria

- [ ] the app has a uniform appearance

## Tasks

- [ ] Explore Brand Identity on surface level
- [ ] Create design guide in Figma
    - [ ] Create style components for elements
    - [ ] Create color scheme
- [ ] Create new branch `style/design`
    - [ ] Apply design to MVP

**Comment by shrocket** [comment]
Hello! And thank you for letting me review your work!
In general, this looks great, but I do have a few comments. Before I make them, I want to mention three things: 
- The acceptance criteria for this US are really vague. What, exactly, does "uniform appearance" mean? How should I, as a QA reviewer, judge whether or not the criteria have been met?
- I looked at your app as though it were on an iPhone SE.
- I looked at your app with Firefox Dev. Ed.

My comments:
- the cancel button on the add trip page is out of whack in two ways:
  - the X icon and the word "Cancel" are on two different lines, and the word "Cancel" hangs outside of the border (this appears to be a browser issue).
  - Even though I looked at this as though it were on an iPhone, I still indulged my habit of tabbing through the form, and found it impossible to tab to the cancel button.
- when I click on the calendar icon, the calendar appears, but then disappears just as quickly (this also appears to be a browser issue).
- the end date of the trip can be after the start date of the trip (I don't think you're offering some kind of time travel trip app)
- Once the trip has been created, both the list view and the details view show the start and end dates in the wrong order!

Here are some screenshots:
![Screenshot 2023-09-28 at 11 46 20](https://github.com/e-rmkt/capstone-project-travel-app/assets/139855611/17d77eee-8c7e-47d1-94d5-29cc7614d9cd)

![Screenshot 2023-09-28 at 11 53 46](https://github.com/e-rmkt/capstone-project-travel-app/assets/139855611/7b4d5a8a-25cd-47df-bef6-2ab13223d6c9)

![Screenshot 2023-09-28 at 11 54 03](https://github.com/e-rmkt/capstone-project-travel-app/assets/139855611/60a41fdd-ca71-4c73-b94b-6cbe5eef5336)

![Screenshot 2023-09-28 at 11 54 16](https://github.com/e-rmkt/capstone-project-travel-app/assets/139855611/badf2062-82dc-4c28-b883-a3bc2707322d)

**Comment by e-rmkt** [comment]
@shrocket Thank you very much for your thorough QA! We really appreciate it and you made us aware of some bugs we would have not discovered until it would be too late probably! ❤️ 

The Firefox situation was valuable hint and we investigated a little. It seems like Firefox interprets the Code differently than Chrome does, which is what we used to check the frontend. We made some changes and the Cancel Button isn't broken anymore. 

The calendar picker bug was also new to us and does not appear in Chrome. This is a bit beyond us though, as the entire date picker stems from `input type="date"` and we tried to change the color for the calendar date picker icon once - horrible experience, would not recommend. But we figured, since you can still type your dates in the input field by hand, the user should still be good to go on Firefox!

As to why you can't select it with tab we are not sure but we have a suspicion. The Cancel Button is actually just a link wearing a fancy button cloak. That is probably why that happens. This is important for accessibility, we noted this issue down and will take care of it in our refactoring next week.

Regarding all the date issues, we are on it! Will be fixed in a different branch that Tobi and Pia are kindly working on right now! :D 

Once again thank you so much! 🚀

**Comment by shrocket** [comment]
@e-rmkt You are most welcome! I would be very interested to know which changes you made to the code to change the cancel button.

Really, it was my pleasure!

**Comment by miriam-ertl** [comment]
Hey Anna,
mostly everything looks very, very good.

- [x] Overview Page looks very good👍🏻
- [x] Detailspage looks very good 👍🏻
- [x] Create New Trip Page looks very good 👍🏻
- [ ] Edit Trip Page needs some adjustment considering the cancel or delete button.  

![Bildschirm­foto 2023-10-02 um 11 53 34](https://github.com/e-rmkt/capstone-project-travel-app/assets/139959429/8a2bbf94-556d-4258-b896-0fc421c44acc)

**Comment by miriam-ertl** [comment]
Dear Ellie, 

- [x] looks totally fine.👍🏻
