### ISSUE TITLE
User Story 7: Location Image

### ISSUE THREAD

**Issue by AnnaD91** [e-rmkt/capstone-project-travel-app#15]
## Value proposition

`As a` travel enthusiast
`I want to` see an image of my destination
`so that`  I can look forward to my upcoming trip with great anticipation 

## Description

![Image](https://github.com/e-rmkt/capstone-project-travel-app/assets/140393240/8996783f-1346-4824-b5c5-3dd5f91e63aa)

## Acceptance criteria

- [ ]  The user sees a random image of their destination on the homepage and the trip detail page
- [ ]  When a trip is created, a random image will be displayed
- [ ]  When a trip is edited (either country or city), a new image corresponding to the changes is displayed

## Tasks

- [ ] create a new `feat/location-image`
- [ ] Choose a suitable API for the images (Pixabay)
   - [ ] Create the necessary API from the page (in `pages/forms/TripForm/index.js` and `pages/forms/TripForm/[id].js`) so the images will be displayed on the homepage and the trip details page 
   - [ ] As soon as the user creates a trip, the according image will be created and the URL will be saved in our collection 
   - [ ] As soon as the user edits a trip (country or city), a new URL will be created and the URL will be edited in our collection 
- [ ] Implement an error handling logic to display an error message if there is an issue loading the image from the API

```

**Comment by JessicaLoers** [comment]
**Well done, and I'm excited to see how it works. 🚀**
Here are some tiny suggestions to improve this US.

**Acceptance criteria**
_You could additionally mention what happens when a trip is changed._
➡️ When a trip is created, the corresponding image will be displayed.
➡️ When a trip is edited (either country or city), a new image corresponding to the changes is displayed.
➡️ If there's an issue fetching the image, an error message should be displayed to the user.
