### ISSUE TITLE
User Story 8: Counter until next Trip

### ISSUE THREAD

**Issue by AnnaD91** [e-rmkt/capstone-project-travel-app#16]
## Value proposition

`As a` travel enthusiast 
`I want to` see how much time is left till my next trip
`so that` I can plan and organise everything for my trip with regard of the time remaining

## Description

![Image](https://github.com/e-rmkt/capstone-project-travel-app/assets/140077651/54f5dcc8-0dad-415e-b233-7d4c4fa4b964)

## Acceptance criteria

- [x] For each trip, the user sees the remaining time both on the homepage as well as on the details page
- [x]  The countdown is displayed in days, for the time remaining until each trip when I visit both the homepage and the trip details page
- [x] If a trip has already passed its start date, it should clearly indicate that the trip is either "Ongoing" or "Past," rather than showing a negative countdown
- [x] The displayed countdown should automatically update each day to show the correct number of days remaining

## Tasks

- [x] Create a feature branch `feat/trip-counter`
- [x] Declare a variable `date` that pulls the current date from `newDate()`
- [x] Show the time difference between `date` and `startDate` in the following components `components/Trip/index.js`and `components/TripList/index.js` in the List element 

```

**Comment by JessicaLoers** [comment]
**What would a user story be without some coach mustard?**  🌭

_Every feature, big or small, holds the potential for a richer set of acceptance criteria._

➡️ The countdown is displayed **in days**, for the time remaining until each trip when I visit both the homepage and the trip details page.

➡️ If a trip has already passed its start date, it should clearly indicate that the trip is either "Ongoing" or "Past," rather than showing a negative countdown. 

➡️  The displayed countdown should automatically update each day to show the correct number of days remaining.

**Comment by miriam-ertl** [comment]
Works totally fine 👍🏻. 
AC and functionality are in pure harmony. 
Very well done.
