### ISSUE TITLE
User Story 9: Confirm Messages

### ISSUE THREAD

**Issue by AnnaD91** [e-rmkt/capstone-project-travel-app#17]
## Value proposition

`As a` travel enthusiast 
`I want to` see a message after clicking on a button 
`so that` so that I know my action was recognised and completed

## Description

![Image](https://github.com/e-rmkt/capstone-project-travel-app/assets/139748392/32293648-1927-4194-bc67-22a01b7fdfb1)

## Acceptance criteria

- [x] Whenever the user clicks on a button, a modal opens 
   - [x] in case of "Create" ("Create"/"Save" Button), the user receives a message of confirmation ("Your trip has been successfully created!") 
       - [x] create -> homepage
       - [x] save -> trip details page
   - [x] in case of "Delete" or "Cancel", the user is asked to confirm their decision by clicking on a button ("Confirm" or "Cancel")
       - [x] cancel -> back to the corresponding form    
       - [x] confirm -> homepage

## Tasks

- [x] Create a feature branch `feat/confirm-messages`
- [x] Create a new component `Modal` in `components/Modal/index.js` 
- [x] Create an `onClick` event for the corresponding buttons to trigger the `Modal `
   - [x] Create Button 
   - [x] Save Button
   - [x] Delete Button 
   - [x] Cancel Button
- [x] Move the functions from the corresponding buttons to the buttons of the `Modal` 

```

**Comment by JessicaLoers** [comment]
**My comments on all your user stories are really nitpicking at a high level. You guys are doing a great job💚**

**Value Proposition**
➡️ so that I know my action was recognized and completed.
👉 _breaks down the process into two distinct steps:_ 
1. recognizing the action
2. completing the action

👉 _emphasizes the UX by highlighting the user's desire to know (rather than just hoping or assuming) that their action had the intended result._

**Comment by shrocket** [comment]
Hello and thank you for letting us look at your work! Here are our comments:

- In the acceptance criteria, you have written "Whenever the user clicks on a button, a modal opens." We would like to point out that the "+" button is a button, but no modal pops up when it is pressed. 😉 
- When deleting a trip, there is no confirmation message "Your trip has been successfully deleted!" We think this should probably be fixed.  (Sorry we missed this in the code . . .)

Thanks again and happy coding!

**Comment by Pia-Lueling** [comment]
Hello Hotel Tishjama 🏨 @shrocket,

thank you very much for your review. Well spotted! We have decided in our group that we will no longer display this message after the delete, because the User journey will be too long for the action! 
It would take the user three button clicks to delete ONE trip! Same applies for the cancel button! But what we implemented instead, that you could kindly test, is a modal that opens up when choosing an end date that is smaller than the start date (in one of the forms either edit form or create form)!
It would be amazing if you could have another look, and if everything works as described, give us the ✅ PLEASE 😝

Love, Peace and Happiness ✌🏽

**Comment by shrocket** [comment]
Hey! That modal that alerts to the end date being before the start date and which then erases all value from the end date field is super nice! 

You changed the US to reflect the loss of the "deleted" confirmation message, why not change the US to show this lovely little thing?

Good work, you lovely people!
