### ISSUE TITLE
User Story 1: List Of Trips

### ISSUE THREAD

**Issue by TobiasSteinhagen** [e-rmkt/capstone-project-travel-app#2]
## Value proposition

`As a` travel enthusiast
`I want to` see all of my trips
`so that` I can easily access relevant information about my trips

## Description

![Image](https://user-images.githubusercontent.com/140353817/268223907-5e7e9e96-8221-45f8-b145-ec64e1ecb4bb.png)

## Acceptance criteria

- [x] On the homepage, there is a list of trips displayed
    - [x] The list has one column
    - [x] The list is vertically scrollable
- [x] Each trip in the list includes the following details:
    - [x] an image of the location
    - [x] the location
    - [x] the time period
    - [x] the individual title
- [x] If there is an issue loading the trip data from the source, an error
  message is displayed to the user
- [x] Each page shows the AppName in the Header component

## Tasks

- [x] Create the collection "Trips" in MongoDB with the mock data
- [x] Create the feature branch 'trip-overview'
- [x] Fetch a list of your trips from the MongoDB collection in the index.js
    - [x] Implement the error handling logic to display an error message if 
      there is an issue loading the trip data from the collection
- [x] Create the component 'Trip', which renders: 
    - [x] an image of the location
    - [x] the location
    - [x] the time period
    - [x] the individual title
- [x] Create the component 'TripList'
    - [x] map through the fetched list of trips and render a 'Trip' component
      for each trip
- [x] In the index.js:
    - [x] render a `<h1> element `for the app name
    - [x] render the 'TripList' component 

<h3> Datenmodell </h3>

```
[
{
"title": "City Trip",
"location": {"country": "Mexico", 
            "city": "Guadalajara"},
"timePeriod": {"startDate": "2023-10-16", 
                "endDate": "2023-11-16"},
"img": "www.irgendeinlink.com/image"
}
]
```
<h3> Schema </h3>

```
const trip = 
{title: String required: true,
location: {
    country: String required: true,
    city: String
            },
timePeriod: {
    startDate: String required: true,
    endDate: String
            },
img: String,
};
```
