### ISSUE TITLE
User Story 11: Weather Feature

### ISSUE THREAD

**Issue by AnnaD91** [e-rmkt/capstone-project-travel-app#25]
## Value proposition

`As a` travel enthusiast 
`I want to` see a weather forecast for my destination 
`so that` I can better prepare for my trip. 

## Description
 

![Image](https://github.com/e-rmkt/capstone-project-travel-app/assets/140393240/9aab972e-d5dc-4153-bc5a-a04c2b68e5f5)

## Acceptance criteria

- [ ] The current weather for each destination is displayed on the trip details page in form of an icon and the unit in Celsius 

## Tasks

- [ ] Create a branch `feat/weather`
- [ ] Choose a suitable weather API 
- [ ] Create a `Weather` component 
- [ ] Fetch weather data from API in `Weather` component 
- [ ] Data is rendered on the trip details page 

```

**Comment by shrocket** [comment]
This looks great!

I imagine, however, that any weather API worth its salt will be able to render the temperature in both Celsius _and_ Fahrenheit. Would it be too much trouble to accommodate our (backwards/non-metric) North American friends?

**Comment by AnnaD91** [comment]
Thanks @shrocket 😊 We had that in mind, but need to see what is possible with the API we choose. If it's easy to implement, we'll include that of course :)

**Comment by miriam-ertl** [comment]
In the QA everything works really nice! Excellent job ★★★★★
