### ISSUE TITLE
User Story 2: Trip Detail Page

### ISSUE THREAD

**Issue by Pia-Lueling** [e-rmkt/capstone-project-travel-app#3]
## Value proposition

`As a` travel enthusiast
`I want to` be able to view further information about a specific trip,
`so that` I can see an overview of the most important details of my trip.

## Description

![Image](https://user-images.githubusercontent.com/139748392/268227287-e6988ea7-a439-4453-ac1d-1f2a900767e3.png)

## Acceptance criteria

- [x] When the user selects a trip from the list on the homepage, they are directed to a dedicated trip detail  page.
- [x] On the trip details page, the user sees the following information:
    - [x] an image of the location
    - [x] the location
    - [x] the time period
    - [x] the individual title
- [x] The user can return to the homepage by clicking a dedicated "Back to Home" link located on the top of the trip details page.

## Tasks

- [x] Create the feature branch `trip-details-page`
- [x] Create the trip details page `pages/trip/[id].js`
- [x] Render the following:
    - [x] add the next.js image component to render the image
    - [x] the location
    - [x] the time period
    - [x] the individual title
    - [x] add the Link component to navigate back to the homepage
- [x] Update the Trip component
    - [x] add the Link component to navigate to the details page
