### ISSUE TITLE
User Story 13: Packing List DELETE

### ISSUE THREAD

**Issue by AnnaD91** [e-rmkt/capstone-project-travel-app#33]
## Value proposition

`As a` travel enthusiast 
`I want to` to be able to delete specific items 
`so that` it does not appear in my packing list anymore. 

## Description

![Image](https://github.com/e-rmkt/capstone-project-travel-app/assets/139748392/0b1d851f-2c01-4a0d-a271-e450759f9de7)

## Acceptance criteria

- [ ] In the packing list is a delete button that deletes an list item 
- [ ]  If the user clicks on the delete button, the item will be deleted 
- [ ]  If there are no more added items, the following message will be displayed in the center of the display "Start your packing list!" with a create button below
- [ ] If there are already added items, the user will see the list of their items

      
## Tasks

- [ ]  Create a feature branch `delete-item`
- [ ]  Create a 'DeleteItemButton' component
- [ ]  By clicking the button, the item will be deleted 
- [ ]  Define a DELETE API route
- [ ]  Connect a handler function which uses this API route

```

**Comment by miriam-ertl** [comment]
★★★★★ Perfect. LGTM.
