### ISSUE TITLE
User Story 14: World Map Feature

### ISSUE THREAD

**Issue by AnnaD91** [e-rmkt/capstone-project-travel-app#34]
## Value proposition

`As a` travel enthusiast
`I want to` see a world map 
`so that` by creating a new trip, a pin is set automatically to the destination in the world map and I get an overview of all my places that I traveled to. 

## Description

![Image](https://github.com/e-rmkt/capstone-project-travel-app/assets/139748392/89759f03-2476-4b3f-86aa-3ca61abd617e)

## Acceptance criteria

- [ ] On the TripList page there is a button on the right corner that says "show map" with a world map icon
- [ ] By clicking on the button, the user will be directed to the world map page
- [ ] The user sees a world map with english titles of cities/countries
- [ ] When a user creates a trip, a pin is automatically set on the destination in the world map
- [ ] When the user deletes a trip, the pin is automatically removed from the world map
- [ ]  When the user clicks on a pin, some details will be shown and the user can go directly to the details page

## Tasks

- [x] create a new feature branch `feat/worldMap`
- [ ] create a new page `pages/worldMap/index.js`
- [ ] Choose a suitable API (i.e. Open Layers)
- [ ] Create a `WorldView` component 
- [ ] Fetch MapData from API in `WorldView` component
- [ ] Data is rendered in `worldMap/index.js`
- [ ] Define a POST API route in a new page api/worldMap/index.js
- [ ] Connect a handler function which uses this API route

`````

**Comment by miriam-ertl** [comment]
Thank you for sharing your US. It was cool reading it and I think it's as cool feature. 
Considering this criteria
- [ ]  By clicking on the button, the user will be directed to the world map page
It would be nice to see the positioning of the button in your mockup. But you could iterate this in a new user story for styling.

**Comment by AnnaD91** [comment]
@miriam-ertl Vielen lieben Dank, dass du dir unsere US angeschaut hast. Das mit dem positioning von dem button hatten wir uns auch erst gedacht, waren dann aber zu faul 🙈 Aber du hast vollkommen recht, spätestens bei der QA hätten wir das Scribble dazu gebraucht. Wir haben es angepasst (siehe oben). 😊
