### ISSUE TITLE
User Story 3: Create A Trip

### ISSUE THREAD

**Issue by TobiasSteinhagen** [e-rmkt/capstone-project-travel-app#4]
## Value proposition

`As a` travel enthusiast
`I want to` be able to create and add new trips to my travel collection,
`so that` I can capture and plan my travel experiences seamlessly.

## Description

![Image](https://user-images.githubusercontent.com/140393240/268291547-867fec9c-f578-41bf-b012-466a18dac023.png)

## Acceptance criteria

- [x] On the homepage is a button that opens a form
     - [x] if there is no trip planned, the following message will be displayed in the center of the display "Create your first trip!" 
            with a button beneath
     - [x] if there are already trips planned, the button will be found in the center of the bottom of the display
- [x]  The form contains the following input fields/elements:
     - [x] Country
     - [x] City
     - [x] Title
     - [x] Start date
     - [x] End Date
     - [x] Create Button
     - [x] Cancel Button (which is a link back to the homepage)
- [x] If the user clicks on the cancel button, the form will be closed and the user will be redirected to the homepage
- [x] If the user clicks on the create button, the form will be closed, the user will be redirected to the homepage and the newly 
       created trip will be shown in the list
- [x] The user can't submit an empty form, if the user tries to submit an empty form, he receives the default message of the form element which fields are required
    

## Tasks

- [x] Create a feature branch 'create-trip'
- [x] Create a 'CreateTrip' component that contains a link (styled as a button)
- [x] Create the 'TripForm' page `pages/forms/TripForm/index.js` that renders a form element which contains the following input fields/elements: 
     - [x] Country (required, type="text", minlength="3")
     - [x] City (type="text")
     - [x] Title (required, type="text", minlength="3")
     - [x] Start date (required, type="date")
     - [x] End date (type="date")
     - [x] Create Button (type="submit")
     - [x] Cancel Button (link styled as a button)     
- [x] Create a 'CreateButton' component 
   - [x] By clicking the button, the trip will be created and the user will be redirected to the index.js (use Mongoose)
      - [x] Define a `POST`  API route
      - [x] Connect a handler function which uses this API route
- [x] Create a 'CancelButton' component, which is a link styled as a button
     - [x] By clicking the link, the user will be redirected to the index.js and the data will not be saved
- [x] Update the index.js
     - [x] render the 'CreateTrip' component
- [x]  Update the 'CreateTrip' component to navigate to the 'TripForm' page

**Comment by JessicaLoers** [comment]
**Very well done**  ✨
I have some comments that will make your user story a bit more precise and detailed.

**Value proposition**
_The value proposition you have chosen functional and direct.
An alternative to this would be a value proposition that is a bit more personal and that notes the benefits of fluid and seamless planning._ 

_This could look like this ⬇️_

**As a travel enthusiast**
**I want to** be able to create and add new trips to my travel collection,
**so that** I can capture and plan my travel experiences seamlessly.


and the other suggestions we talk about 🙃

**Comment by JessicaLoers** [comment]
Good job and almost done ✨

- The user can't submit an empty form
➡️ _Please explain what happens or better what notification users see when they try to submit a blank form._
**Example**
- if the user tries to submit a blank form, an error message is displayed indicating which fields are mandatory. 

- Cancel Button (type="reset")
➡️  _This button is rather a link that navigates users back to the Overview page. 
Of course, you could think about an additional option of resetting the form._ 

**Example**
-  Cancel button which directs the user back to the overview page

**Tasks**
 - Create a 'CancelButton' component
   - By clicking the button, the form will be emptied and the user will be redirected to the index.js

➡️ _As already mentioned, it is necessary to distinguish between a reset and an abort. 
If you write a function that includes both the reset and the navigation, the reset is obsolete._
