### ISSUE TITLE
User Story 4: Delete a Trip

### ISSUE THREAD

**Issue by TobiasSteinhagen** [e-rmkt/capstone-project-travel-app#5]
## Value proposition

`As a` travel enthusiast
`I want to` delete a specific trip
`so that` it does not appear in my trip list anymore.

## Description

![Image](https://user-images.githubusercontent.com/140393240/268303076-f1ae3e62-ab23-462d-8d16-1a52d3c878c7.png)

## Acceptance criteria

- [x] On the details page is a delete button that deletes the trip
- [x] If the user clicks on the delete button, the trip will be deleted and the user will be redirected to the homepage
    - [x] If there are no more trips planned, the following message will be displayed in the center of the display "Create your first          trip!" with a button beneath
    - [x] If there are still more trips planned, the user will see the list of their trips

## Tasks

- [x] Create a feature branch `delete-trip`
- [x] Create a 'DeleteButton' component 
   - [x] By clicking the button, the trip will be deleted and the user will be redirected to the index.js (use Mongoose)
      - [x] Define a `DELETE`  API route
      - [x] Connect a handler function which uses this API route

**Comment by JessicaLoers** [comment]
**Nice User Story ✌️**

**Attention, a smarty-pants remark is coming up 😁**
It is not easy to write Value Propositions, it takes experience and practice. 
The user benefit you described is already clearly, but if you want to make it a bit more concise or "user-centric", you could try this:

- so that I can keep my travel list always up to date and clear.
