### ISSUE TITLE
User Story 5: Edit a Trip

### ISSUE THREAD

**Issue by TobiasSteinhagen** [e-rmkt/capstone-project-travel-app#9]
## Value proposition

`As a` travel enthusiast
`I want to` edit a specific trip
`so that` I can update my trips if changes are necessary.

## Description

![Image](https://user-images.githubusercontent.com/140393240/269218259-6adcc158-e321-40d1-9428-ea117cd48a36.png)

## Acceptance criteria

- [ ] On the details page is a link (styled as a button) to edit the trip
- [ ] If the user clicks on the link, the trip will be opened in the form element (including the values) and the user can edit the values
- [ ] The user can save or cancel their changes
     - [ ] By clicking the save button, the user will be redirected to the details page of the trip and see their changes
     - [ ] By clicking the cancel button, the user will be redirected to the details page of the trip and see no changes

## Tasks

- [x] Create a feature branch `edit-trip`
- [x] Define a `PUT` API route in the api/trips/[id].js
### New EditButton Component (components/EditButton/index.js)
- [x] Create a Link  component EditButton styled as a Button
- [x] pass the id prop to the EditButton component
- [x] add an href to link to `/forms/TripForm/${id}`
### DetailsPage (pages/[id].js)
- [x] Update the DetailsPage `pages/trip/[id].js` to render the EditButton
### TripForm (pages/forms/TripForm/${id})
- [x] Create the submit handler `handleEditTrip` and connect it with the API route  
     - [x] the user can save without any changes as well                   
     - [x] the user can cancel without any changes as well 
- [x] duplicate the form from `pages/forms/TripForm/index.js`
- [x] fetch the values for the specific trip that is edited via useSWR
- [x] replace the placeHolder texts with defaultValues of the specific trip that is edited
- [x] Change text of CreateButton to "Save"
### CreateButton Component (components/CreateButton/index.js)
- [x]  Refactor the CreateButton, so that the static input will be replaced with {children}

**Comment by shrocket** [comment]
I am not at all surprised by how good this looks! I am also super jealous of your exceptionally beautiful task-list . . . !

The only thing (and this is really really picky--like Erbsensplitterei par excellence) is the period at the end of the final line in the value proposition. I understand that the VP is a sentence unto itself, but then it should also make use of commas in the correct places.

I'll put one of these ✅ in Slack, and a few of these here: 🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀
